using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public class PlayerBall : MonoBehaviour
{
    public float jumpPower;
    public int itemCount;
    bool isJump;
    Rigidbody rigid;
    AudioSource audio;

    void Awake()
    {
        isJump = false; 
        rigid = GetComponent<Rigidbody>();
        audio = GetComponent<AudioSource>();

    }

    void Update()
    {
        if(Input.GetButtonDown("Jump") && !isJump)
        {
            isJump = true;
            rigid.AddForce(new Vector3(0, jumpPower, 0), ForceMode.Impulse);
        }
    }

    void FixedUpdate()
    {
        float h = Input.GetAxisRaw("Horizontal");  
        float v = Input.GetAxisRaw("Vertical");                          
       
        rigid.AddForce(new Vector3(h, 0, v), ForceMode.Impulse);

    }

    void OnCollisionEnter(Collision collision) 
    {
        if (collision.gameObject.name == "Floor") 
            isJump = false; 
    }

    void OnTriggerEnter(Collider other)
    {
        if(other.name == "Item_Banana")
        {
            itemCount++;
            audio.Play();
            other.gameObject.SetActive(false);

        }
    }


}
